/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidateMagicLinkRouteImport } from './routes/validateMagicLink'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SsoRouteImport } from './routes/sso'
import { Route as RequestNewPasswordRouteImport } from './routes/requestNewPassword'
import { Route as RequestMagicLinkRouteImport } from './routes/requestMagicLink'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedManagerReportsRouteImport } from './routes/_authenticated/manager/reports'
import { Route as AuthenticatedManagerLayoutRouteImport } from './routes/_authenticated/manager/_layout'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin/jobs'
import { Route as AuthenticatedAdminLayoutRouteImport } from './routes/_authenticated/admin/_layout'

const ValidateMagicLinkRoute = ValidateMagicLinkRouteImport.update({
  id: '/validateMagicLink',
  path: '/validateMagicLink',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoRoute = SsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestNewPasswordRoute = RequestNewPasswordRouteImport.update({
  id: '/requestNewPassword',
  path: '/requestNewPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestMagicLinkRoute = RequestMagicLinkRouteImport.update({
  id: '/requestMagicLink',
  path: '/requestMagicLink',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerReportsRoute =
  AuthenticatedManagerReportsRouteImport.update({
    id: '/manager/reports',
    path: '/manager/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerLayoutRoute =
  AuthenticatedManagerLayoutRouteImport.update({
    id: '/manager/_layout',
    path: '/manager',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminLayoutRoute =
  AuthenticatedAdminLayoutRouteImport.update({
    id: '/admin/_layout',
    path: '/admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/requestMagicLink': typeof RequestMagicLinkRoute
  '/requestNewPassword': typeof RequestNewPasswordRoute
  '/sso': typeof SsoRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/validateMagicLink': typeof ValidateMagicLinkRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminLayoutRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/manager': typeof AuthenticatedManagerLayoutRoute
  '/manager/reports': typeof AuthenticatedManagerReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/requestMagicLink': typeof RequestMagicLinkRoute
  '/requestNewPassword': typeof RequestNewPasswordRoute
  '/sso': typeof SsoRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/validateMagicLink': typeof ValidateMagicLinkRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminLayoutRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/manager': typeof AuthenticatedManagerLayoutRoute
  '/manager/reports': typeof AuthenticatedManagerReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/requestMagicLink': typeof RequestMagicLinkRoute
  '/requestNewPassword': typeof RequestNewPasswordRoute
  '/sso': typeof SsoRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/validateMagicLink': typeof ValidateMagicLinkRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin/_layout': typeof AuthenticatedAdminLayoutRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/manager/_layout': typeof AuthenticatedManagerLayoutRoute
  '/_authenticated/manager/reports': typeof AuthenticatedManagerReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/requestMagicLink'
    | '/requestNewPassword'
    | '/sso'
    | '/unauthorized'
    | '/validateMagicLink'
    | '/account'
    | '/admin'
    | '/admin/jobs'
    | '/admin/roles'
    | '/admin/users'
    | '/manager'
    | '/manager/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/requestMagicLink'
    | '/requestNewPassword'
    | '/sso'
    | '/unauthorized'
    | '/validateMagicLink'
    | '/account'
    | '/admin'
    | '/admin/jobs'
    | '/admin/roles'
    | '/admin/users'
    | '/manager'
    | '/manager/reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/requestMagicLink'
    | '/requestNewPassword'
    | '/sso'
    | '/unauthorized'
    | '/validateMagicLink'
    | '/_authenticated/account'
    | '/_authenticated/admin/_layout'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/users'
    | '/_authenticated/manager/_layout'
    | '/_authenticated/manager/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RequestMagicLinkRoute: typeof RequestMagicLinkRoute
  RequestNewPasswordRoute: typeof RequestNewPasswordRoute
  SsoRoute: typeof SsoRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ValidateMagicLinkRoute: typeof ValidateMagicLinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validateMagicLink': {
      id: '/validateMagicLink'
      path: '/validateMagicLink'
      fullPath: '/validateMagicLink'
      preLoaderRoute: typeof ValidateMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso': {
      id: '/sso'
      path: '/sso'
      fullPath: '/sso'
      preLoaderRoute: typeof SsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requestNewPassword': {
      id: '/requestNewPassword'
      path: '/requestNewPassword'
      fullPath: '/requestNewPassword'
      preLoaderRoute: typeof RequestNewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requestMagicLink': {
      id: '/requestMagicLink'
      path: '/requestMagicLink'
      fullPath: '/requestMagicLink'
      preLoaderRoute: typeof RequestMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/reports': {
      id: '/_authenticated/manager/reports'
      path: '/manager/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof AuthenticatedManagerReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/_layout': {
      id: '/_authenticated/manager/_layout'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/_layout': {
      id: '/_authenticated/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminLayoutRoute: typeof AuthenticatedAdminLayoutRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedManagerLayoutRoute: typeof AuthenticatedManagerLayoutRoute
  AuthenticatedManagerReportsRoute: typeof AuthenticatedManagerReportsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminLayoutRoute: AuthenticatedAdminLayoutRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedManagerLayoutRoute: AuthenticatedManagerLayoutRoute,
  AuthenticatedManagerReportsRoute: AuthenticatedManagerReportsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RequestMagicLinkRoute: RequestMagicLinkRoute,
  RequestNewPasswordRoute: RequestNewPasswordRoute,
  SsoRoute: SsoRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ValidateMagicLinkRoute: ValidateMagicLinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
